# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

def shared_pods
  pod 'IQKeyboardManager'
  # add the Firebase pod for Google Analytics
 # pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  # Pods for SampleReactNativeChat
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'
  
  pod 'QBImagePickerController', :path => '../node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePickerController.podspec'

  use_native_modules!

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
#  pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'

 

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'


  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'
  
  pod 'react-native-razorpay',:path=>'../node_modules/react-native-razorpay'
  #pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

end


target 'Shopikuchbhi' do
  shared_pods
end


target 'QuikShop' do
  shared_pods

end


target 'Artycrafts' do
  shared_pods
end



## Uncomment the next line to define a global platform for your project
#platform :ios, '10.0'
#require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
#
#
#target 'QuikShop' do
#  pod 'IQKeyboardManager'
#  pod 'Firebase/Messaging'#, '~> 6.13.0'
#  # add the Firebase pod for Google Analytics
##  pod 'Firebase/Analytics'
##  # add pods for any other desired Firebase products
##  # https://firebase.google.com/docs/ios/setup#available-pods
#  # Pods for SampleReactNativeChat
#  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
#  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
#  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
#  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
#  pod 'React', :path => '../node_modules/react-native/'
#  pod 'React-Core', :path => '../node_modules/react-native/'
#  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
#  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
#  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
#  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
#  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
#  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
#  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
#  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
#  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
#  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
#  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
#  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
#
#  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
#  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
#  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
#  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
#  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
#  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
#  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
#
#  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
#  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
#  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'
#
#  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
#
# pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
#
# pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'
#
#  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
#
#  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
#  pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'
#  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
#
#  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'
#
#  pod 'react-native-razorpay',:path=>'../node_modules/react-native-razorpay'
#
#
#
# # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
#
# # pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'
#
#  #pod 'react-native-webview', :path => '../node_modules/react-native-webview'
#
#  #pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
#  #pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'
#
#
#
#  # pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
#
#
#  # pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'
#
#  # pod 'react-native-razorpay',:path=>'../node_modules/react-native-razorpay'
#  #pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
#
#  #pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'
#
#  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
#
#  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
#   # use_native_modules!
#
#end
